### ISSUE TITLE
has dll for php5.5 in windows with redis cluster support?

### ISSUE THREAD

**Issue by sjdskl** [phpredis/phpredis#1072]
i want to use php_redis for windows with redis cluster support in php5.5.
but i cant build it at  windows and there is no useful dll for download
http://windows.php.net/downloads/pecl/releases/redis/3.1.0/

**Comment by michael-grunder** [comment]
Hi,

It appears that all php 5.x builds are failing (on PECL) since 2.2.8.  Unfortunately, I don't have a Windows machine, nor do I know the process by which one would go about building this in Visual Studio.

I believe you may find what you're looking for here, although this will be essentially 2.2.8 (does contain cluster support though):
https://github.com/phpredis/phpredis/issues/754

Cheers,
Mike

**Comment by sjdskl** [comment]
I have modify php redis source code to  build  pass at the windows。
https://github.com/sjdskl/phpredis_windows

thanks for your help @michael-grunder
