### ISSUE TITLE
delete method returns false for php 7

### ISSUE THREAD

**Issue by pcfreak30** [phpredis/phpredis#1170]
Having a case on wordpress where I can get a cache key but using del/delete on the same key returns false. I switched to predis and its working perfectly.

It appears to be broken on php 7, as 5.6 works fine.

using PHP 7.0.18-1~dotdeb+8.1 and redis extension version 3.1.1.

**Comment by michael-grunder** [comment]
Without more information it's hard to say for sure what the problem is.  That being said, are you able to try with the current version of phpredis (3.1.2)?

If you're still having issues I'm happy to help track it down.

**Comment by pcfreak30** [comment]
No, this is on cloudways managed provider with a client site. Not in position to upgrade but your 3.1.2 changelog mentions nothing about anything related to this so i doubt its fixed there.

If you spin up a server there with wordpress, use the redis-cache plugin, and use xdebug, you can trace it down to the redis object calls. I don't know what more info to give right now.

**Comment by michael-grunder** [comment]
There isn't any way I can help diagnose the problem without more information.

You can query `getLastError()` to see if that has any specific information as to why the delete failed.  You could also run the unit tests `php tests/TestRedis.php` from that environment to see if anything seems to be going wrong.

You can also use Predis.  It's a great library and no further investigation is needed.

**Comment by pcfreak30** [comment]
@michael-grunder predis seemed to run 3x slow so switched to memcached.

Will try the unit tests.

**Comment by pcfreak30** [comment]
Deleting the hStrLen test since 3.1.1 doesnt have the method it seems, heres the result.

https://gist.github.com/pcfreak30/6cce660d0ff5799580d10b86cf24a993

**Comment by michael-grunder** [comment]
I assume the warnings have to do with running current unit tests with an older version of phpredis.   We changed a few methods between 3.1.1 and 3.1.2.

That being the case things look to be working.  The delete test seemed to work.  It's possible that you are running into stability issues with 3.1.1 which are fixed in 3.1.2.  I'm not sure what the process is to get the extension upgraded, but I would recommend the hosting company do it.  3.1.2. has been released on PECL for a while now.
