### ISSUE TITLE
Is version 3.1.3 coming any time soon?

### ISSUE THREAD

**Issue by pb66** [phpredis/phpredis#1175]
following issue #1156 there was a fix https://github.com/phpredis/phpredis/commit/4e56ba804cdfcaae36b98f1bbdcf9ffb4e77b6e2 committed and I wondered when this would filter through to PECL.

Please understand I'm not chasing, just trying to decide whether we should look at editing our own documentation to recommend v2.2.8 for php5 systems in the interim, obviously we look forward to being able to recommend one version of phpredis regardless of php version for simplicity etc.

We really appreciate you resolving the issue in the first instance so apologies if my question suggests any impatience, that's not the case at all.

Thanks in advance.

**Comment by michael-grunder** [comment]
Hey,

I think we should get another release up to PECL as there have been a few fixes implemented since it was released.  The trick is going to be where to cut the release, as I would be a bit nervous pushing the present `develop` branch up with so many changes:

```bash
➜  phpredis git:(develop) ✗ git diff tags/3.1.2 develop --stat|tail -n1
 24 files changed, 1830 insertions(+), 2549 deletions(-)
```
A great deal of that came from refactoring how we construct commands which _should_ be safe enough but needs more time being used to make sure.

I'll take a look this evening at what changes we might want to include for a 3.1.3 release and update this thread.

**Comment by pb66** [comment]
That sounds great, thank you!

**Comment by spike3312** [comment]
Hi guys,

Just wondering if there has been any movement on this as my installation is struggling with version 3.1.2.

**Comment by michael-grunder** [comment]
I'll get something ready for packaging today.  I need to go through the history to determine which commits to include, because I don't want to include everything that is in develop now.

Git makes this reasonably easy though.

**Comment by yatsukhnenko** [comment]
3.1.3 was released yesterday

**Comment by remicollet** [comment]
Looks like 3.1.3 introduce some regressions

Various users my my [repository](https://rpms.remirepo.net/)  reports about segfault after upgrade (at least with PHP 5.4 and 5.6).
Downgrade to 3.1.2 solves it 

Ex: https://github.com/remicollet/remirepo/issues/75
