### ISSUE TITLE
zRange：The integer score will be converted to a floating point number

### ISSUE THREAD

**Issue by lizhilei** [phpredis/phpredis#1189]
I insterd data to redis
```
zadd zset_test 3888153779537508 3888153779537508
```
When i get it with the following code
```
<?php
        $redis = new Redis();
        $redis->connect('127.0.0.1', 6379);
        var_dump($redis->ZRANGE("zset_test", 0, -1, true));
```
It become
```
array(1) {
  [3888153779537508]=>
  float(3.8881537795375E+15)
}
```
when I get it from redis， it‘s correct
```
redis> zrange zset_test 0 -1 withscores
1) "3888153779537508"
2) "3888153779537508"
redis>
```

I do not know where the problem is?

**Comment by michael-grunder** [comment]
Hey,

I checked as far back as version 2.2.7 and phpredis seems to have always worked this way.  The scores in a Redis zset are stored internally as double precision floating point numbers, and are returned to phpredis in string representation which phpredis treats as a float.

You're seeing scientific notation because PHP likes to do this automatically for large floating point numbers.  It would be possible for phpredis to perform additional processing on the returned score to determine if it is a whole number but there is a performance cost to this.

**Comment by lizhilei** [comment]
Thank you very much for your reply。
I had used version 2.2.2 for years. In version 2.2.2 it return the score as string. 
I am very curious that why  converted the score to a float?

**Comment by lizhilei** [comment]
The function will return like this

```
array(1) {
  [3888153779537508]=>
  string(16) "3888153779537508"
}
```

**Comment by lizhilei** [comment]
The function will renturn like this in php 5.6  and php-redis 2.2.2
```
array(1) {
  [3888153779537508]=>
  string(16) "3888153779537508"
}
```
