### ISSUE TITLE
Delete operation not available on Redis cluster

### ISSUE THREAD

**Issue by Rudigern** [phpredis/phpredis#1268]
### Expected behaviour
To be able to use delete()
### Actual behaviour
Have to use del()

### I'm seeing this behaviour on
- OS: CentOS 7
- Redis: 3.2.6
- PHP: 5.6
- phpredis: latest

### Steps to reproduce, backtrace or example script
Use Redis cluster

### I've checked

- [-] Issue isn't fixed in `develop` branch

When moving to Redis cluster my delete operation failed due to it being undefined. Looked in redis_cluster.h and it's not mentioned, only del. Figured this was just an oversight as doco refers to del,delete

**Comment by michael-grunder** [comment]
Hi,

I'm torn on this issue.  DELETE isn't a Redis command, it's an alias for DEL that phpredis included way before I was involved on the project.

When I implemented redis cluster I didn't bring those aliases to the new functionality but tried to maintain a one to one mapping of actual redis commands to phpredis command functions.

So in other words this was intentional on my part.  That being said it's not a technical issue (creating an alias is a one liner in an extension) and I can see the argument that it makes porting easier, but there are other subtle changes I can't get around (e.g. any command that has to be delivered to a node like echo or ping).

At the very least it should be clarified in the documentation though.

**Comment by Rudigern** [comment]
I know what you mean, I guess I got caught up because in the documentation examples it uses delete(), so thats what I used when using a single node. It took me 5 seconds to change once I realised, however it probably should be consistent.

**Comment by xergio** [comment]
In redis.c, delete() execute a DEL command, and del() is an alias of delete(). What a mess...

In redis_cluster.c is almost perfect, no alias, only del() function executing the DEL command.

**Comment by michael-grunder** [comment]
Hi @xergio,

Like I mentioned before, this is intentional.  These aliased commands were created at the inception of this project, for reasons I'm not really clear on.  In order to not break existing code we left the aliases in the `Redis` object.

There is no `DELETE` command in Redis, only `DEL`.  We are going to release version 5.0.0 soon which only supports php7 so perhaps we will remove the aliases then.

**Comment by michael-grunder** [comment]
I'm going to close this issue, because I don't plan on adding `DELETE` (or any other non redis commands) to the RedisCluster object.

**Comment by Rudigern** [comment]
I don't think adding delete should be done however this isn't documented as far as I can tell. Shouldn't `DELETE` be deprecated and just move to a consistent `del` as it aligns to Redis?

**Comment by Nowi5** [comment]
What would be the right way for may older packages to support DEL with redis-cluster?
Currently having the issue "Cannot use 'DEL' with redis-cluster"
