### ISSUE TITLE
Cluster connection needs to be closed after an exception to avoid wrong values being read

### ISSUE THREAD

**Issue by nicofff** [phpredis/phpredis#1418]
An issue was reported in #1222 where read timeout exceptions would leave the connection in a bad state and returning bad data until the connection was closed.  
The issue was partially resolved. 

a) At time of writing (using the develop branch) when a read timeout exception occurs only one wrong value is read.
b) As a workaround, persistent connections can now be closed.

Per discussion [here](https://github.com/phpredis/phpredis/issues/1222#issuecomment-426405492) a proper fix is doable, opening this issue to track the implementation and use it as reference in documentation.

**Comment by radykal-com** [comment]
Hello, 

after some research, this issue describes pretty well the bug we are seeing in our production environment:

- OS: Ubuntu
- Redis: 5
- PHP: 7.2
- phpredis: 4.2.0

For some reason, we are reading wrong data sometimes, we ask for key "a" with a specific data structure and are getting back the value from another key with another data. 

With a very fast pooling testing script we are always getting the correct values of all affected keys, so seems is the extension that for some reason is reading wrong values under any specific circumstance.

Our setup is using a php-fpm pool with like 400 processes, persistent connections and the options to distribute reads across masters and slaves. Each server handles lots of requests per second. We didn't find any way to reproduce the error in any other environment than production. If we disable persistent connections the issue is fixed, but we would like to prevent disabling them.

Any guidance on how to debug this problem?

**Comment by yatsukhnenko** [comment]
@radykal-com connection pooling was implemented in 4.3.0

**Comment by radykal-com** [comment]
But AFAIK this issue has nothing to do with connection pooling. Or is it? Persistent connections should return the right value or just crash, getting wrong data is so weird.

**Comment by yatsukhnenko** [comment]
No time to explain :smile:
All problems with persistent connections and wrong data caused by how PHP engine shares persistent resources between objects and how phpredis handle this.

**Comment by radykal-com** [comment]
Hehehe thanks you, then with 4.3.0 is it fixed? Only when connection pools are enabled?

Thanks

**Comment by radykal-com** [comment]
Hi again,

We are using version 4.3.0 (with connection pools enabled) for two days and we are still getting wrong data randomly.

Is there any way we could debug what is causing the problem?
