### ISSUE TITLE
Persistent connections?

### ISSUE THREAD

**Issue by roelmonnens** [phpredis/phpredis#1420]
Could you explain when persistent connections should work and when they don't?
In my research about this I'm finding lots of contradictions about this subject.

In my own use case I can't get it to work. The connections are presistent but aren't reused.
I'm using aggregated connections (RedisArray) to 3 or more redis machines. My PHP code runs with nginx/php-fpm (all latests versions).

**Comment by KoteKotlyarov** [comment]
Up.

Guys, I want to know how PHP-REDIS handles persistent connections. Did your module do this ? Did the PHP ? Will it work when PHP works as CGI ? Or it will work only with Apache MPMs or php-fpm ?

Who handles opened sockets, connections and processes for them ?

I need to deploy changes into all my PHP sites. Those changes will force additional API request into 3rd party api and I need to be sure that whole instance will reuse connections/sockets/processes otherwise my high load server will consume all free sockets and spam hundreds of processes for php-curl. I just can't test it in such environment...

**Comment by sylfabre** [comment]
Up.

Some documentation about persistent connections would be greatly appreciated.
I understand that there is the `pconnect` method, the `redis.pconnect.pooling_enabled` setting and that 4.3.0 version brings "proper persistent connections pooling implementation" but that's all.
Please add some documentation about:
- when it's expected to work and when it's not (throw some exception maybe when using `pconnect` in an unsupported environment instead of falling back to `connect`?)
- how to use the `persistent_id` argument, mostly what happens when left to it's default value?
- questions raised in #1328

This package is really great and seems to be the fastest one as PHP client (good work there!) but it sometimes lacks a bit of documentation to properly use it :)

**Comment by sylfabre** [comment]
Ping @yatsukhnenko as you have worked on this matter for the 4.3.0 release !

**Comment by yatsukhnenko** [comment]
My knowledge of English is not enough for writing documentation 😅
Phpredis uses persistent connection mechanism represented by PHP engine.
> when it's expected to work and when it's not

I don't know situations when pconnect wouldn't work. Persistent connection is keeping alive while process is running and server doesn't close the connection from its side.

> how to use the persistent_id argument, mostly what happens when left to it's default value

persistent_id is an unique identifier for finding stream object in the hash `EG(persistent_list)`. When you don't set it from your code phpredis uses hostname + port as persistent_id.

When connection pooling is enabled phpredis stores linked list in persistent storage. The elements of this list is stream objects created by PHP engine. Phpredis desides to close the stream or to return it to the list for future requests.

**Comment by yatsukhnenko** [comment]
Resolved
