### ISSUE TITLE
How to use redis in windows with php 5.6.35 from scratch step by step

### ISSUE THREAD

**Issue by qualitysof** [phpredis/phpredis#1498]
good morning, I am new to use Redis and I would like to know how to use redis from the installation setup and an example of using the server as the client.

thank you very much for your help.

Johnny Tarmeño
qualitysof@gmail.com

**Comment by michael-grunder** [comment]
Hi @qualitysof,

I don't have a Windows machine, so I can't give step-by-step instructions on how to make this work, but I'm guessing there are some tutorials online that might help.

[Installing PHP Extensions in windows](http://php.net/manual/en/install.pecl.windows.php)
[Prebuilt DLLs for PhpRedis](https://pecl.php.net/package/redis)

Redis doesn't officially support Windows, but this might be helpful:
[Running Redis on Windows 10](https://redislabs.com/blog/redis-on-windows-10/).

There is also an older, forked version of Redis which apparently works in Windows:
https://github.com/MicrosoftArchive/redis

I'm closing the issue, since this isn't really a bug in Phpredis.  I hope you're able to get it working though. :smile:

**Comment by qualitysof** [comment]
Sorry if the question is not for this forum, what I'm looking for is how to update a field of a table when the user closes a tab or the browser, I was thinking about doing it with workers but I do not know if it is the best idea.

If you have an example about that or an idea, I would appreciate it.

**Comment by michael-grunder** [comment]
That sounds more like a question about JavaScript.

[This might be relevant](https://stackoverflow.com/questions/3888902/detect-browser-or-tab-closing)

You might have luck asking in these places:
https://www.reddit.com/r/learnjavascript/
https://www.reddit.com/r/CodingHelp/
https://www.reddit.com/r/learnprogramming/

**Comment by qualitysof** [comment]
yes, I test with javascript, but javascript functions do not work for some browsers
