### ISSUE TITLE
Problem with Pthreads and Volatile Objects

### ISSUE THREAD

**Issue by BoltUser** [phpredis/phpredis#1546]
Hi, 
i'm trying to using phpredis on pthreads projects, and when i use a Volatile objects the PhpRedis extension do not work.

I receive this error : Redis server went away 

I have this error only if i extend the class where using Redis object with Volatile, if i not extend the class with Volatile all work fine, but on my project and in many pthreads projects the Volatile class are necessary.

### Actual behaviour

 Redis server went away 

### I'm seeing this behaviour on
- OS: Debian 9
- Redis: 5.0.3
- PHP: 7.2
- phpredis: latest

### Steps to reproduce, backtrace or example script

you can compile pthreads and use php with ZTS and try to create a class where you using Redis Object, this class must be extended from Volatile.

### I've checked
- [X ] There is no similar issue from other users
- [ ] Issue isn't fixed in `develop` branch

**Comment by michael-grunder** [comment]
Hi, @BoltUser sorry for the delay in responding.

I haven't used the pthreads extension personally, but it's unlikely that phpredis is thread-safe out of the box, since we don't have any threading logic at all.

Can you post a small example of how you're trying to use phpredis with the Volatile class?  I can then step through the execution to get an idea about how it's supposed to work.

It would be pretty cool if phpredis could operate in a multithreaded way but typically that requires a lot of custom synchronization code.

**Comment by yatsukhnenko** [comment]
@michael-grunder if I'm not mistaken all that TSRMLS_DC/TSRMLS_CC in code is for thread safety ;)

**Comment by michael-grunder** [comment]
Yeah, the `TSRMLS_*` structs are PHP's magical thread safety voodoo construct for ZTS but I'm not sure if that in and of itself will be enough to work with phpredis.

It would be cool, but from the report appears that it doesn't work out of the box.

**Comment by michael-grunder** [comment]
Without more information we can't really fix this issue.

@BoltUser Feel free to reopen the issue if you can post a small program so we can reproduce the problem.
