### ISSUE TITLE
protocol error, got 'W' as reply type byte

### ISSUE THREAD

**Issue by saurabh-gohil** [phpredis/phpredis#1585]
I am getting following error and I can't seem to find the solution for it.

```
PHP Fatal error:  Uncaught RedisException: protocol error, got 'W' as reply type byte

 in /opt/process/P3B_4_extractIFANew3.php:48
Stack trace:
#0 /opt/process/P3B_4_extractIFANew3.php(48): Redis->debug('82ff876670d9d89...')
#1 {main}
  thrown in /opt/process/P3B_4_extractIFANew3.php on line 48

```
Please help me and let me know if more information is required.

### I'm seeing this behaviour on
- OS: CentOS Linux release 7.2.1511  
- Redis: 5.0.3
- PHP: PHP 7.0.18
- phpredis: 4.2.0

### I've checked
- [x] There is no similar issue from other users

**Comment by michael-grunder** [comment]
Hi @saurabh-gohil,

The `protocol error, got '<char>' as reply type byte` is something that typically happens if PhpRedis gets out of sync with Redis for some reason.  

Most commonly it happens when people are using persistent connections and experience a timeout or other such errror.  Then, when PhpRedis attempts to use the connection again, it's already in the middle of a reply causing the protocol error.

So the first question I'd ask is whether you're using `pconnect`.  It's worth mentioning that we've made a great deal of improvements around persistent connection reuse since 4.2.0, so it might be possible to fix your problem simply by upgrading PhpRedis.

**Comment by out001a** [comment]
I got the same error occasionally when using `pconnect`
* PHP: 7.2.13
* Redis: 2.8.14
* phpredis: 4.2.0

**Comment by yatsukhnenko** [comment]
@saurabh-gohil, @out001a try to update to 4.3.0 and enable connection pooling

**Comment by yatsukhnenko** [comment]
Should be fixed in the latest stable version
