### ISSUE TITLE
Github release information

### ISSUE THREAD

**Issue by heddn** [phpredis/phpredis#1635]
### Expected behaviour

Release information provided for this project at https://api.github.com/repos/phpredis/phpredis/releases/latest, similar to https://api.github.com/repos/php-memcached-dev/php-memcached/releases/latest and https://api.github.com/repos/igbinary/igbinary/releases/latest.

For more info, refer to https://developer.github.com/v3/repos/releases/#get-the-latest-release

### Actual behaviour
I get a Not Found error message.

### I'm seeing this behaviour on
- OS: n/a
- Redis: n/a
- PHP: n/a
- phpredis: n/a

### Steps to reproduce, backtrace or example script
See above.

### I've checked
- [x ] There is no similar issue from other users
- [x ] Issue isn't fixed in `develop` branch

**Comment by heddn** [comment]
This seems useful: https://github.community/t5/How-to-use-Git-and-GitHub/Why-last-release-is-not-marked-as-quot-latest-release-quot/td-p/1762

**Comment by remicollet** [comment]
Probably because this project don't use all **github** features, but use **pecl** ones.

Lot of pecl extensions don't use github, but git.php.net (and a github mirror), so also don't (and can't) use these features

Changelog is available on https://pecl.php.net/package-changelog.php?package=redis
(pecl web site also have an API, which is consumed by the pecl command)

IMHO: important project information, such as changelog, should be store in a tracked file, in git, rather than relying on some hosting features to avoid adherence to this hosting.

BTW still possible to do thing twice.

**Comment by heddn** [comment]
Pecl goes away in PHP 7.4. So I'm looking to build from source.

For example with memcached, I can use:

`curl -fsSL $(curl -s https://api.github.com/repos/php-memcached-dev/php-memcached/releases/latest | grep "tarball_url" | cut -d : -f 2,3 | tr -d \",) | tar xvz -C /tmp/memcached --strip 1`

**Comment by heddn** [comment]
But in the mean time, trying to use the pecl api: https://pear.php.net/rest/r/redis/latest.txt returns 404.

**Comment by heddn** [comment]
And I don't see it listed on https://pear.php.net/rest/p/packages.xml

**Comment by heddn** [comment]
For now, using `$(curl -I https://pecl.php.net/get/redis |awk 'BEGIN {FS="-"}/^Content-Disposition/{print $3}'| cut -f 1-3 -d '.')` to get the latest version.

**Comment by michael-grunder** [comment]
Closing as I made a release :smile:
https://api.github.com/repos/phpredis/phpredis/releases/latest
