### ISSUE TITLE
PHP Warning:  Unknown: Failed to write session data (redis)

### ISSUE THREAD

**Issue by julienbornstein** [phpredis/phpredis#188]
I'm trying to use redis for session handler.

```
PHP Warning:  Unknown: Failed to write session data (redis). Please verify that the current setting of session.save_path is correct (tcp://127.0.0.1:6379?weight=1) in Unknown on line 0
```

also tried with : 

```
session.save_path = "127.0.0.1:6379"
session.save_path = "tcp://127.0.0.1:6379"
session.save_path = "tcp://127.0.0.1:6379/" (this one crash)
```

but failed....

But I can use redis functions

this work 

```
$redis = new Redis();
$redis->connect('127.0.0.1', 6379);
$test = $redis->set('mytest', 'myvalue');
$test = $redis->get('mytest');
echo (print_r($test,1));
```

config in php.ini :

```
session.save_handler = redis
session.save_path = "tcp://127.0.0.1:6379?weight=1"
```

Using Ubuntu 11.10 + PHP-FPM (5.3.10-1ubuntu3.1) + nginx (1.1.19-1)

**Comment by yeszao** [comment]
In my case, `session.gc_maxlifetime`  was the reason. I get the error because  `session.gc_maxlifetime` was set to 144000000000. it will overflow and become a non-positive expire time passed to Redis.

These just delete the key, see: https://redis.io/commands/expire.

I had tested that the maximum expire time in Redis was 2147483647 (0x7fffffff).

So, I solved this issue by set `session.gc_maxlifetime = 3600`.

Other issue explain same problem: https://github.com/phpredis/phpredis/issues/184

**Comment by yatsukhnenko** [comment]
Old issue without any activity for a long time.

**Comment by Emik123dsa** [comment]
If it still works for somebody,
I actually could resolve this issue with truncating my password, when I have generated it with openssl.
`session.save_path="tcp://localhost:6379?auth=xxxx"`, cause it didn't work before.

**Comment by choironguk** [comment]
i had the same problem.
maybe you can try to below in php.ini set like this and then it's working
session.save_path = "tcp://localhost:6379?database=10"

i was setup session.save_path = "tcp://127.0.01:6379?database=10"  and then Appeared this problem
