### ISSUE TITLE
keys() returns keys with prefix, but it receives pattern without prefix

### ISSUE THREAD

**Issue by npelov** [phpredis/phpredis#2397]
$redis->setOption(Redis::OPT_PREFIX, 'test:');
$redis->set("var1", "value1");
$keys = $redis->keys("var*");
var_dump($keys);

### Expected behaviour

array(1) {
  [0] =>
  string(12) "var1"
}

### Actual behaviour
array(1) {
  [0] =>
  string(12) "testing:var1"
}

### I'm seeing this behaviour on
- OS: CentOS 7
- Redis: 5.0.5-3.el7
- PHP: php-7.3 and php-8.1
- phpredis: 6.0.0

### Steps to reproduce, backtrace or example script
$redis->setOption(Redis::OPT_PREFIX, 'test:');
$redis->set("var1", "value1");
$keys = $redis->keys("var*");
var_dump($keys);

### I've checked
- [X] There is no similar issue from other users (similar but not sure if it's the same: 2369)
- [X] Issue isn't fixed in `develop` branch

**Comment by michael-grunder** [comment]
This issue has been around since the very early days of PhpRedis.

It's not really a bug per se, but more a design decision.  Also we can't "fix" it by changing default behavior, so the only potential solution would be to introduce a new `Redis::OPT_*` constant to enable the functionality you're looking for.

Honestly, over the years we have come to the conclusion that this is easy enough to do in userland PHP code, that we're not sure it's really worth implementing in PhpRedis itself.

@yatsukhnenko What do you think.

**Comment by yatsukhnenko** [comment]
In my opinion we shouldn't handle this on PhpRedis side but I'll approve PR with new `Redis::OPT_*` if you would like to implement this 🙃

**Comment by michael-grunder** [comment]
I don't really think it's worth building in PhpRedis either.
