### ISSUE TITLE
Automatic reconnects don't re-authenticate

### ISSUE THREAD

**Issue by atdt** [phpredis/phpredis#403]
The fact that redis reconnects transparently but does not authenticate the new connection means that from the client's perspective a connection is liable to silently lose its authenticated status. Like #76, this is another bit of state that needs to be reconfigured when phpredis reconnects.

**Comment by Kyoshiro-san** [comment]
Hello,

I tried to add authentication on my redis server, but then the application failed with PHP Fatal error:  **Uncaught RedisException: Failed to AUTH connection**. I checked what was happening with tcpdump and it seems the PHP application is doing this : 
* connect to redis (payload follows) :
```
AUTH xxxx
+OK
SELECT 0
+OK
GET my_value
$-1
```
* reconnect to redis server from another local port  (payload follows) :
```
SELECT 0
-NOAUTH
```
As you can see, Redis server is complaining about NOAUTH, probably because it's using a new socket (in the same PHP process). I tried adding persistent = true and then false to the code, but it didn't change anything.

I also checked for server issue by sending the commands manually from the same connection using netcat and it works as expected.

I figure I have stumbled upon this precise bug but if that's not the case, please tell me where to look. Is there maybe a solution to allow authentication on php7.0-redis to work ?

I'm using dotdeb.org PHP7 / FPM / modules packages for debian jessie.
Cheers

**Comment by yatsukhnenko** [comment]
Automatic reconnection works fine. Feel free to reopen this issue if needed.
