### ISSUE TITLE
HHVM compatibility

### ISSUE THREAD

**Issue by gordyr** [phpredis/phpredis#457]
With HHVM and HACK really beginning to gain popularity I would be great to see phpredis get ported to the HHVM extension format,  our love of phpredis is the only thing keeping us from using HHVM.

**Comment by junedahmed** [comment]
Couldn't agree with @gordyr more. Phpredis is the next best thing after redis itself and due to the robustness of the extension, I dedicated countless nights developing custom module to 'load-balance' each data + mysql query to redis. That being said, 140% of my mysql data is in redis now a days! Can't wait to see HHVM compatible extension to port my applications.

**Comment by i-sam** [comment]
agree with @junedahmed about using with HHVM

**Comment by cklepeis** [comment]
Got my vote as well.

**Comment by hws47a** [comment]
any progress?

**Comment by HaiNguyen007** [comment]
+1

**Comment by yatsukhnenko** [comment]
I don't think that we would ever support hhvm.
