### ISSUE TITLE
Function "redis_sock_disconnect" in client.c not using the "QUIT" properly

### ISSUE THREAD

**Issue by schlitzered** [phpredis/phpredis#562]
Hey,

we found a problem in the PHPRedis client while debugging another Redis related Problem.

From http://redis.io/commands/quit

"""
Ask the server to close the connection. The connection is closed as soon as all pending replies have been written to the client.
Return value

Simple string reply: always OK
"""

But instead this happens in redis_sock_disconnect:
1. write QUIT
2. close the connection

This leads to TCP [RST] messages from the client, because the server is trying to at least send the "OK" response to the "QUIT"

I would suggest to simply close the underling connection from the client side, or if you think you realy need to call "QUIT", to also wait for the "OK" response.

cheers

schlitzer

**Comment by michael-grunder** [comment]
Hey,

Interesting.  I think you're correct.  I'm not an expert in the IP layer itself, so I wonder if there is an advantage to sending QUIT vs. just closing the connection.  If we do continue to send the QUIT command I'll wait for the reply.

Cheers!
Mike

**Comment by schlitzered** [comment]
Hey Mike, 

from the low level TCP point of view, there is no advantage.

I think the reason to send the QUIT command is to make sure that the server has no more data to send.

But if i am rigth, PHPRedis is always waiting for the result to return after a request was made. So simply calling .close on the connect will be sufficient.

cheers,

schlitzer

**Comment by michael-grunder** [comment]
OK thank you for the information.  I will update the code and get it pushed into develop!

Cheers!
Mike

**Comment by chuanma** [comment]
We encountered the same issue on our production server.  Based on http://redis.io/commands/quit, the `quit` command ask the *server* to close the connection. Based on tcp protocol (http://en.wikipedia.org/wiki/Transmission_Control_Protocol#/media/File:Tcp_state_diagram_fixed_new.svg), redis server will stay on `TIME_WAIT` state because it's the *redis server* that starts the closing process. 

On a busy server, it means that the redis server would have tens of thousands connections in `TIME_WAIT` state, which will easily run out of available ip port. In our case, we see 17k connections in `CLOSING` state because phpredis sent back `RST` packet in response to the redis server's `OK` packet. So those connections on redis server were actually stuck before reaching the `TIME_WAIT` state.

So that `QUIT` command is problematic. By doing that, phpredis tells *the server* to close the connection. But phpredis immediately close the connection by itself right after sending out `QUIT` command, leaving the `OK` response from redis server to trigger the `RST` response. So we should remove that command. The redis python client doesnt' send back the `QUIT` command, for example:

https://github.com/andymccurdy/redis-py/blob/master/redis/connection.py#L519-L529
```python
    def disconnect(self):
        "Disconnects from the Redis server"
        self._parser.on_disconnect()
        if self._sock is None:
            return
        try:
            self._sock.shutdown(socket.SHUT_RDWR)
            self._sock.close()
        except socket.error:
            pass
        self._sock = None
```

**Comment by chuanma** [comment]
Sending `QUIT` will ask the redis server side to close the connection. That's not going to scale on high traffic server, because that leaves the redis server to deal with connections in TIME_WAIT/COSING states. Instead, those states should only appear on client side, because normally we have more clients than servers.

**Comment by chuanma** [comment]
@michael-grunder I can send a pull request if you agree. Let me know.

**Comment by chuanma** [comment]
This is a wireshark screenshot for the packets captured on our redis server. In the screenshot, redis server initiated the closing connection process. But phpredis side has already closed the connection. So phpredis sent back a `RST` packet.  Then redis server side tried to retransmit a number of times until it run of the maximum number of tcp retries.

![image](https://cloud.githubusercontent.com/assets/325845/6793281/a5264756-d198-11e4-8c8f-f3253c5a1f60.png)

**Comment by eliaw** [comment]
Another side affect of sending quit is that it doesn't integrate cleanly with [twemproxy](https://github.com/twitter/twemproxy).  Twemproxy currently by default does not accept the QUIT signal and logs it as an error which was polluting our logs at a very high rate.  Thus, we'd also like the quit signal to be removed from redis_sock_disconnect.

**Comment by chuanma** [comment]
We can't wait until this issue is fixed because our redis server has so many connections stuck in `CLOSING` state, also causing random 'Redis Server Went Away' RedisException on php side. 

An alternative solution we did is to use persistent connection (switch to `pconnect()`). Hope it helps some people who are in same situation right now.

**Comment by silentroach** [comment]
Could you please make a new stable extension version with this fix?

**Comment by hashar** [comment]
Seems d701d02f9c has been released and is part of non release candidates tags:

3.1.1 
3.1.0
3.0.0
2.2.8
