### ISSUE TITLE
PECL version

### ISSUE THREAD

**Issue by remicollet** [phpredis/phpredis#565]
I saw tags in github (2.2.6 and 2.2.7) but nothing on PECL which is still the preferred sources for various users, including downstream distributions, including Microsoft build for Windows, available from pecl website (automatically raised when a new version is upload there).

**Comment by michael-grunder** [comment]
@remicollet Right after I pushed 2.2.6 there were a few non-trivial bugs discovered (including ZTS breaking compile typos) so that version was scrapped.  2.2.7 has been up for quite a while and as of yet nothing that would prevent me from packaging it up, so I think I'm OK to move forward.

Sorry for the delay guys.  Also, if anybody running windows wants to verify that there aren't any compile breaking changes since 2.2.5 that would be brilliant as I don't have a windows build environment.

Cheers!
Mike

**Comment by pierrejoye** [comment]
@michael-grunder  needs MSDN? That will let you install all you need in a VM to do testing (along many other things, aka all Msft software)

**Comment by weltling** [comment]
@michael-grunder you might have received some mails from the build system, but to be sure ... i've triggered the build http://windows.php.net/downloads/pecl/snaps/redis/2.2.5/  . The build passes so far, so if you release *today*, it'll come through.

Though please be aware that the build bot still recognizes it as 2.2.5, so it overwrote an older snapshot. That should be probably fixed before packaging.

Thanks.

**Comment by mediocregopher** [comment]
@michael-grunder Sorry to nag, but is there any update on getting 2.2.7 onto pecl?

**Comment by michael-grunder** [comment]
@mediocregopher Not nagging. :smiley:  I have just been really focused on cluster support as of late.  Packaging is not overly difficult.  I'll see about taking a couple hours tonight and try to get it up.  

Thanks for the reminder!

**Comment by mediocregopher** [comment]
:sheep: nag

**Comment by michael-grunder** [comment]
Hey, I've uploaded the package but to be quite honest I'm terrible at packaging things.  If you run into any issues let me know and I'll package it up again.

3.0.0 coming soon :)

**Comment by remicollet** [comment]
I just run some build (RPM for Fedora / RHEL / CentOS). Everything seems Ok.

Thanks for this release.

**Comment by mediocregopher** [comment]
awesome, thanks @michael-grunder
