### ISSUE TITLE
[redis cluster] causing cluster state to fail

### ISSUE THREAD

**Issue by Ewan-GrandSlam** [phpredis/phpredis#615]
I am in the middle of converting a Predis application to phpredis and upon changing it almost immediately caused the cluster to set its state to: fail - All stats requests would then return CLUSTERDOWN until the cluster state went back to: ok.

Could it be that with predis I am using hashing with my keys (e.g. 'mykey:{38}') ? if you guys need more information let me know

**Comment by michael-grunder** [comment]
In theory there should be no way for phpredis (or any client library) to cause the server itself to fail.  Have you verified that Redis itself goes into a CLUSTERDOWN state?  The only thing I can think of is if the server and client are on the same machine and phpredis is causing you to run out of file descriptors such that Redis can no longer communicate with all of the nodes).  

This doesn't seem likely because Redis will already have those connections open, but I suppose it's possible.

Cheers
Mie

**Comment by Ewan-GrandSlam** [comment]
To pain a better picture of the setup:

2 servers, 6 nodes on each server none of which have very high load (maybe 5% when they are not writing to disk).

We have identified an issue with timeouts that we have since addressed and have not tried to use phpredis again since.Basically it was almost forming a new connection on every single command because it would drop out the old ones immediately causing a high volume of connect time outs.

**Comment by michael-grunder** [comment]
Hey,

Thanks for the additional information.  I need to enable persistent connections as an option for phpredis which should mitigate this problem.  I'll link to this issue when I have that up.

Cheers!
Mike
