### ISSUE TITLE
[PHP7 Branch] Expire 0 no longer means "no expiration"

### ISSUE THREAD

**Issue by steffenweber** [phpredis/phpredis#732]
```
<?php
$redis = new Redis();
$redis->connect('localhost');
$redis->set('key', 'value', 0);
```

Using PHP 5.6.17 and phpredis 2.2.7 this yields `"SET" "key" "value"`. Fine.

But using PHP 7.0.2 and the current HEAD of the `php7` branch the same code sends nothing to the Redis server (observed using `redis-cli` with the `MONITOR` command). I guess this is a bug because IMHO the old behaviour (`0` meaning "no expiration") is more intuitive.

**Comment by zzjin** [comment]
@steffenweber Same error here. But find reason at 01b46d0dc96085e2a6872ac9a3d42e50bab6d7  .
But the latest release version was too old, and not included this fix.

**Comment by seyfer** [comment]
I had encountered this issue with  phpredis 2.2.8 and php 5.6.24
and have spent about one working day to guess why redis doesn't save value.

**Comment by yatsukhnenko** [comment]
Probably fixed

**Comment by steffenweber** [comment]
I've tested again using PHP 7.1.17 and PhpRedis 3.1.3RC2: the bug is still there.

**Comment by michael-grunder** [comment]
Hey guys,

I'm not totally sure what the best thing to do is here.  It is correct that the functionality changed from 2.2.7 -> 2.2.8, but the change is actually more correct from a Redis standpoint.  Using a zero second expire is an error, and Redis will report it as such:

```
127.0.0.1:6379> setex foo 0 bar
(error) ERR invalid expire time in setex
```

Additionally, the 2.2.7 functionality is potentially more dangerous as it will silently write a never expiring key if sent a zero timeout.  I believe this issue was raised by a different bug report while 2.2.8 was in progress.

I don't think changing the functionality back to what it was in 2.2.7 is really an option, as it's certain to break lots of people's code.

@yatsukhnenko Perhaps we could issue a warning to the user if sent an invalid expire argument?

**Comment by steffenweber** [comment]
Thank you for the feedback. I did not know that Redis reports an error for expire = 0.

That being said, the PhpRedis 2.2.7 behaviour still makes more sense to me from a PHP API perspective (for example, it mirrors the `expire` parameter of the `setcookie` function where `0` means "never expires").

On the other hand, I *personally* have adjusted my code and therefore have no problem at all with keeping the PhpRedis 2.2.8+ behaviour.

**Comment by yatsukhnenko** [comment]
@michael-grunder `set` command returns `false` which means failure. This is enough to understand that 0 is not valid expire value.
