### ISSUE TITLE
misbehaviour using phpredis as cache for laravel

### ISSUE THREAD

**Issue by n1kt0** [phpredis/phpredis#734]
when using the redis cache driver from laravel with phpredis and redis unstable version first login attempt results in maximum login attempts although it is the first one. when switching to cache driver with file caching everything works fine. somehow the get method of phpredis returns for the given key in redis some value which is interpreted from laravel as true and therefore executes the if-statement.

**Comment by michael-grunder** [comment]
I'm not familiar with laravel.  Do they wrap phpredis?

**Comment by n1kt0** [comment]
they use it in their cache implementation when you mean this with wrapping. did the return value of get change in the past in your implementation? i ask because they expect null as return value instead of false when a key isn't found.

**Comment by jonathanpmartins** [comment]
@n1kt0 Laravel implements https://github.com/nrk/predis, you are in the wrong repository!
Tip for you! Use memcached as cache! And if you use redis,for something, use this repository, ```phpredis```. I think it is easy to use and in my production tests, it was much faster.

**Comment by jonathanpmartins** [comment]
@michael-grunder I think this issue can be closed!

**Comment by n1kt0** [comment]
i wanted to use only phpredis because of the performance you mentioned and i'm not satisfied with an solution of using two libs for the same task. i'm going to alter the laravel implementation for that. but could you tell me the main reasons for you using memcached as cache because i read many times that memcached is "out-dated".

**Comment by jonathanpmartins** [comment]
@n1kt0 I use memcached because is made for caching. Redis can be used too, but it is more advanced. Its good for other reasons.

The same reason I use memcached for caching is that I use Beanstalkd for queues. One problem, one simple and direct solution.

Cache = Memcached
Queues = Beanstalkd
Redis = Key/value par DB / PubSub functionality, etc...

- Yes, If I will, I can use Redis for cache, Redis for queues and Redis for everything. But when comes to make a simple task work, I prefer to use a simple program that solve my simple problems.

In another hand I dont think memcached is out of date. If you take a look at https://github.com/php-memcached-dev/php-memcached/tree/php7 you can see the active development. Note: the php7 package is not ready yet, but you can use it with php5 normaly. If you use ubuntu type: ```sudo apt-get install php5-memcached```

**Comment by n1kt0** [comment]
i fixed the code for me and the issue can be definitely closed. i've also
configured beanstalkd additionaly. perhaps i should rethink it and use
redis for everything. perhaps it behaves slightly better because there is
lesser inter process synchronization. with out of date i didn't mean that
it's not maintained anymore. it will be still maintained because of
widespreaded use.

2016-02-05 16:57 GMT+01:00 Jonathan Martins <notifications@github.com>:
