### ISSUE TITLE
phpredis compile error

### ISSUE THREAD

**Issue by mrluciusfox** [phpredis/phpredis#782]
Hi,
I've got this error when trying to compile:

/bin/bash /home/mr/workspace/phpredis/libtool --mode=compile cc  -I. -I/home/mr/workspace/phpredis -DPHP_ATOM_INC -I/home/mr/workspace/phpredis/include -I/home/mr/workspace/phpredis/main -I/home/mr/workspace/phpredis -I/usr/include/php5 -I/usr/include/php5/main -I/usr/include/php5/TSRM -I/usr/include/php5/Zend -I/usr/include/php5/ext -I/usr/include/php5/ext/date/lib  -DHAVE_CONFIG_H  -g -O2   -c /home/mr/workspace/phpredis/redis.c -o redis.lo 
libtool: compile:  cc -I. -I/home/mr/workspace/phpredis -DPHP_ATOM_INC -I/home/mr/workspace/phpredis/include -I/home/mr/workspace/phpredis/main -I/home/mr/workspace/phpredis -I/usr/include/php5 -I/usr/include/php5/main -I/usr/include/php5/TSRM -I/usr/include/php5/Zend -I/usr/include/php5/ext -I/usr/include/php5/ext/date/lib -DHAVE_CONFIG_H -g -O2 -c /home/mr/workspace/phpredis/redis.c  -fPIC -DPIC -o .libs/redis.o
In file included from /usr/include/php5/main/php.h:208:0,
                 from /home/mr/workspace/phpredis/common.h:1,
                 from /home/mr/workspace/phpredis/redis.c:27:
/usr/local/include/pwd.h:8:1: error: unknown type name 'LIST'
make: *** [redis.lo] Error 1

The file pwd.h seems to be part of boost library, i don't know why it is located in /usr/local/include directory.

/* Copyright Vladimir Prus 2002. Distributed under the Boost */
/* Software License, Version 1.0. (See accompanying */
/* file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt) */

#ifndef PWD_H
#define PWD_H

LIST* pwd(void);

#endif

**Comment by michael-grunder** [comment]
Hey,

This is a new one which has caused me to go down the rabbit hole that is boost :smiley:

Full disclosure here, I don't use boost and don't have it installed on my system but can make a guess.  `pwd.h` is a core system include on linux:

```
http://pubs.opengroup.org/onlinepubs/7908799/xsh/pwd.h.html
```

It is also as you mentioned part of the boost library and defines this `LIST` stucture:

```
https://github.com/davidsiaw/boost/blob/master/tools/build/v2/engine/pwd.h
```

The problem is that with the way your system is configured it's finding the `boost` version of `pwd.h` before (or instead of) the system version.  You probably have the real `pwd.h` in `/usr/include` and perhaps you have `/usr/local/include` first in path?

Sorry I can't give you a specific fix for this, other than to say that it's an include path problem however your system is set up.

I hope that at least helps!

Mike

**Comment by mrluciusfox** [comment]
Thanks a lot @michael-grunder !!!
