### ISSUE TITLE
when use redis sentinel,how to use the phpredis?

### ISSUE THREAD

**Issue by bain2018** [phpredis/phpredis#854]
when use redis sentinel,how to use the phpredis?
i have 3 redis server, one master and two slave, and set the sentinel to monitor all of the redis server.

how can i use the phpredis to connect the redis  master server?
if the master server down and changed by the sentinel.do the phpredis have the function the check it and auto change the config to connect the master.

thank u.

**Comment by giantninja** [comment]
I'd love to have an answer to this as well

**Comment by mcouillard** [comment]
Seems the common way to handle this void is to place HAproxy in front. Your app talks to HAproxy . HAproxy talks with each backend to determine the master and uses whatever the current master is. The slaves are not used; they receive passive replication until the master goes down upon which Sentinel will promote 1 to master. HAproxy will detect this new master and use it.

Your app thinks it is talking with a single Redis server because phpredis is configured to use a single IP:port (HAproxy).

This post describes it all really well: [http://engineering.bloomreach.com/the-evolution-of-fault-tolerant-redis-cluster/](url)
