### ISSUE TITLE
Issues with set with third option 

### ISSUE THREAD

**Issue by ravenbyron** [phpredis/phpredis#859]
Hello,

 I have two issues

1) We had some code that was trying to do `set(key,value, array('nx', 'ex' => .25)` in version <2.2.8 this would set the key if it didn't exist with no ttl. In version 2.2.8 it started just returning false.  I feel like this should throw an exception that ex must be integer.

2) I was working to fix my code for the above problem and the documentation says

```
// Will set a key, if it does exist, with a ttl of 1000 miliseconds
$redis->set('key', 'value', Array('xx', 'px'=>1000));
```

But this did not work 
`$redis->set('key', 'value', Array('nx', 'px'=>10));`
Is this a documentation bug that the `'xx'` should be `'nx'` or is this a lower level bug? This behavor was the same on v2.2.7 and v2.2.8.

Thanks
Byron

**Comment by michael-grunder** [comment]
Hey,

This is a known issue and is actually due to a fix made between 2.2.7 and 2.2.8.  setting `ex` to a number  < 1 is actually an error in Redis, so phpredis was modified to match that functionality.

The problem other people were having is that they were passing 0 into the ex option and then having keys never time out.  

So it's sort of a catch-22 situation.  I can see the usefulness in both behaviors but it should certainly inform the user so it's easier to track down if an invalid timeout is specified.

**Comment by michael-grunder** [comment]
Hey,

From the redis documentation:

> NX -- Only set the key if it does not already exist.
> XX -- Only set the key if it already exist.

I just did a bit of testing, and this seems to work correctly.

**Comment by seyfer** [comment]
I guess this issue have the same nature as this one
https://github.com/phpredis/phpredis/issues/732

**Comment by yatsukhnenko** [comment]
Old issue without any activitu for a long time
