### ISSUE TITLE
if one server of redis cluster is down, hang occur on session_start()

### ISSUE THREAD

**Issue by cwmin** [phpredis/phpredis#883]
Hi, michael-grunder

I have a problem with redis cluster.
## my environment is
- php version :  5.3.28
- phpredis version
  2.2.8 
  session.save_handler = rediscluster
  session.save_path = "seed[]=192.168.77.218:6378&seed[]=192.168.77.218:6379&seed[]=192.168.77.218:6380&seed[]=192.168.77.218:6381&seed[]=192.168.77.219:6378&seed[]=192.168.77.219:6379&seed[]=192.168.77.219:6380&seed[]=192.168.77.219:6381&seed[]=192.168.77.134:6378&seed[]=192.168.77.134:6379&seed[]=192.168.77.134:6380&seed[]=192.168.77.134:6381&timeout=1&read_timeout=1&failover=error"
- redis cluster
  server A [master master slave slave]
  server B [master master slave slave]
  ## server C [master master slave slave]
1. shutdown 'server A'
2. I found hang on php file execution (hang line is session_start()) during 4 seconds.

I want to resolve this problem.

Thank you

**Comment by cwmin** [comment]
I am waiting a reply T T

**Comment by adlagares** [comment]
Hello,

we have found a problem that could bu related with this. Using phpredis-3.1.4 and php-7.1.19.

When Redis Cluster seeds are distributed in same ports of differents hosts (IPs) the method cluster_init_seeds of cluster_library.c only register one seed by port in HasTable.

This problem occurs because the variable redis_sock->host is used as input parameter of method zend_hash_str_update_ptr at line 915 to calculate the seed Hash and is always evaluated as empty string. redis_sock->host is a zend_string typed pointer so it should be treated with ZSTR_VAL function instead passing it directly.

A topology example to ilustrate this problem would be the next:

Server A                                                               Server B
198.168.0.10:6379 (master, slots 0..5400)            198.168.0.11:6379 (slave, slots 0..5400)
198.168.0.10:6380 (slave, slots 5401..10800)       198.168.0.11:6380 (master, slots 5401..10800)
198.168.0.10:6381 (master, slots 10801..16383)  198.168.0.11:6381 (slave, slots 10801..16383)

When all of six seeds are declared only three of them will be registered in HasTable so, when one of the servers is down, phpredis returns error "Couldn't map cluster keyspace using any provided seed" even when the Cluster state is OK.

We have solved this problem applying the attached patch in 3.1.4 version of phpredis.

Best regards.
[cluster_library.zip](https://github.com/phpredis/phpredis/files/1482349/cluster_library.zip)

**Comment by yatsukhnenko** [comment]
@adlagares, nice catch! Could you create a pull request with your fix instead of attaching zip archive?

**Comment by yatsukhnenko** [comment]
@adlagares 6202047

**Comment by adlagares** [comment]
@yatsukhnenko sorry for not creating a Pull Request. I´m newbe at github so I was reading about collaboration workflow before forking.

I will create Pull Request next time!
